spring:
  datasource:
    url: jdbc:mysql://localhost:3300/webdemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: **********
    driver-class-name: com.mysql.cj.jdbc.Driver
    application:
      name: springboot-jwt
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/oldsheep/mapper/xml/*.xml
server:
  port: 8000

config:
  jwt:
    # 加密密钥
    secret: ********
    # token有效时长
    expire: 3600
    # JWT负载中拿到的开头
    head: Bearer

data:
  elasticsearch:
    repositories:
      enabled: true
    cluster-nodes: localhost:9300 # es的连接地址及端口号
    cluster-name: elasticsearch # es集群的名称
